spring:
  datasource:
    url: jdbc:postgresql://10.42.208.3:5432/jobboard
    username: postgres
    password: bounswe2025jobboard
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ethicaljobb@gmail.com # gmail: cotsezer2000@gmail.com
    password: tnsbklpzewntduqe # google apps password: abcd efgh ijkl mnop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1d

server:
  port: 8080

app:
  jwt:
    secret: ThisIsASecretKeyThatIsAtLeast32Chars
    expiration: 86400000  # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

file:
  upload-dir: /app/uploads/profile-pictures