import 'workplace_brief_info.dart';

/// Represents a job posting.
class JobPost {
  final String id;
  final String employerId;
  final String title;
  final String description;
  final WorkplaceBriefInfo? workplace;
  final bool remote;
  final bool inclusiveOpportunity;
  final bool nonProfit;
  final String? salaryRange;
  final String? contactInformation;
  final DateTime? postedDate;
  final int? minSalary;
  final int? maxSalary;

  // Legacy fields for backward compatibility (computed from workplace)
  String get company => workplace?.companyName ?? '';
  String get location => workplace?.location ?? '';
  String get ethicalTags =>
      workplace?.ethicalTags.join(',') ?? '';
  
  // Computed salary range for backward compatibility
  String? get salaryRange {
    if (minSalary != null && maxSalary != null) {
      return '\$${minSalary} - \$${maxSalary}';
    } else if (minSalary != null) {
      return '\$${minSalary}+';
    } else if (maxSalary != null) {
      return 'Up to \$${maxSalary}';
    }
    return null;
  }

  JobPost({
    required this.id,
    required this.employerId,
    required this.title,
    required this.description,
    this.workplace,
    required this.remote,
    required this.inclusiveOpportunity,
    this.nonProfit,
    this.contactInformation,
    this.postedDate,
    this.minSalary,
    this.maxSalary,
  });

  // Factory constructor for JSON parsing (GET /api/jobs/{id} or GET /api/jobs)
  factory JobPost.fromJson(Map<String, dynamic> json) {
    // Helper to safely parse date
    DateTime? parseDate(String? dateString) {
      if (dateString == null) return null;
      try {
        return DateTime.parse(dateString);
      } catch (e) {
        print("Error parsing date: $dateString, Error: $e");
        return null; // Return null if parsing fails
      }
    }

    return JobPost(
      // Assuming API returns string IDs, convert int if necessary
      id:
          json['id']?.toString() ??
          (throw Exception('Missing required field: id')),
      employerId:
          json['employerId']?.toString() ??
          (throw Exception('Missing required field: employerId')),
      title:
          json['title'] ?? (throw Exception('Missing required field: title')),
      description:
          json['description'] ??
          (throw Exception('Missing required field: description')),
      workplace:
          json['workplace'] != null
              ? WorkplaceBriefInfo.fromJson(
                json['workplace'] as Map<String, dynamic>,
              )
              : null,
      remote:
          json['remote'] ?? (throw Exception('Missing required field: remote')),
      inclusiveOpportunity: json['inclusiveOpportunity'] ?? false,
      nonProfit: json['nonProfit'] as bool?,
      contactInformation: json['contact'],
      postedDate: parseDate(json['postedDate']),
      minSalary: json['minSalary'] as int?,
      maxSalary: json['maxSalary'] as int?,
    );
  }

  // Method to convert JobPost instance to JSON (for POST /api/jobs)
  // Only includes fields specified in backend API
  // Note: id, employerId, and postedDate are generated by backend
  Map<String, dynamic> toJsonForCreate(int workplaceId) {
    return {
      'workplaceId': workplaceId,
      'title': title,
      'description': description,
      'remote': remote,
      'inclusiveOpportunity': inclusiveOpportunity,
      if (nonProfit != null) 'nonProfit': nonProfit,
      if (contactInformation != null) 'contact': contactInformation,
      if (minSalary != null) 'minSalary': minSalary,
      if (maxSalary != null) 'maxSalary': maxSalary,
    };
  }

  // Method to convert JobPost instance to JSON (for PUT /api/jobs/{id})
  // Matches backend API specification - id is in path, employerId from auth token
  Map<String, dynamic> toJsonForUpdate(int workplaceId) {
    return {
      'workplaceId': workplaceId,
      'title': title,
      'description': description,
      'remote': remote,
      'inclusiveOpportunity': inclusiveOpportunity,
      if (nonProfit != null) 'nonProfit': nonProfit,
      if (contactInformation != null) 'contact': contactInformation,
      if (minSalary != null) 'minSalary': minSalary,
      if (maxSalary != null) 'maxSalary': maxSalary,
    };
  }
}
