package org.bounswe.jobboardbackend.activity.model;

public enum ActivityType {
    REGISTER,
    UPDATE_PROFILE,
    CREATE_WORKPLACE,
    CREATE_JOB,
    APPLY_JOB,
    APPROVE_APPLICATION,
    REJECT_APPLICATION,
    CREATE_REVIEW,
    REQUEST_MENTORSHIP,
    ACCEPT_MENTORSHIP,
    COMPLETE_MENTORSHIP,
    CREATE_THREAD,
    CREATE_COMMENT,
    UPVOTE_THREAD,
    DOWNVOTE_THREAD,
    EDIT_THREAD,
    DELETE_THREAD
}
