version: '1.0'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
#    healthcheck:
#      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
    networks:
      - app-network
    volumes:
      - ./apps/backend/uploads:/app/uploads
      - backend-data:/app/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: app-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  backend-data:
    name: app-backend-data