import 'dart:convert';

/// Represents a job posting.
class JobPost {
  final String id;
  final String employerId;
  final String title;
  final String description;
  final String company;
  final String location;
  final bool remote;
  final String ethicalTags;
  final String? salaryRange;
  final String? contactInfo;
  final String? jobType;
  final DateTime? datePosted;

  JobPost({
    required this.id,
    required this.employerId,
    required this.title,
    required this.description,
    required this.company,
    required this.location,
    required this.remote,
    required this.ethicalTags,
    this.salaryRange,
    this.contactInfo,
    this.jobType,
    this.datePosted,
  });

  // Factory constructor for JSON parsing (GET /api/jobs/{id} or GET /api/jobs)
  factory JobPost.fromJson(Map<String, dynamic> json) {
    // Helper to safely parse date
    DateTime? parseDate(String? dateString) {
      if (dateString == null) return null;
      try {
        return DateTime.parse(dateString);
      } catch (e) {
        print("Error parsing date: $dateString, Error: $e");
        return null; // Return null if parsing fails
      }
    }

    return JobPost(
      // Assuming API returns string IDs, convert int if necessary
      id:
          json['id']?.toString() ??
          (throw Exception('Missing required field: id')),
      employerId:
          json['employerId']?.toString() ??
          (throw Exception('Missing required field: employerId')),
      title:
          json['title'] ?? (throw Exception('Missing required field: title')),
      description:
          json['description'] ??
          (throw Exception('Missing required field: description')),
      company:
          json['company'] ??
          (throw Exception('Missing required field: company')),
      location:
          json['location'] ??
          (throw Exception('Missing required field: location')),
      remote:
          json['remote'] ?? (throw Exception('Missing required field: remote')),
      // Assuming ethicalTags is returned as a single string
      ethicalTags: json['ethicalTags'] ?? '', // Default to empty string if null
      // Optional fields from GET potentially not in DTO
      salaryRange: json['salaryRange'],
      contactInfo: json['contactInfo'],
      jobType: json['jobType'],
      datePosted: parseDate(json['datePosted']), // Use helper for safe parsing
    );
  }

  // Method to convert JobPost instance to JSON (for POST /api/jobs)
  // Only includes fields specified in JobPostDto
  Map<String, dynamic> toJsonForCreate() {
    return {
      // id is generated by backend, employerId might be path/header param or in body
      // If employerId needs to be in body for POST, add it here.
      // 'employerId': employerId,
      'title': title,
      'description': description,
      'company':
          company, // Assuming company comes from employer or needs to be sent
      'location': location,
      'remote': remote,
      // Sending ethicalTags as a string.
      'ethicalTags': ethicalTags,
    };
  }

  // Method to convert JobPost instance to JSON (for PUT /api/jobs/{id})
  // Includes potentially updatable fields
  Map<String, dynamic> toJsonForUpdate() {
    return {
      // id is usually in the path for PUT
      // employerId might be fixed or updatable depending on API design
      'employerId': employerId,
      'title': title,
      'description': description,
      'company': company,
      'location': location,
      'remote': remote,
      'ethicalTags': ethicalTags, // Send as String
      // Include other fields if they are updatable via PUT
      'salaryRange': salaryRange,
      'contactInfo': contactInfo,
      'jobType': jobType,
      // datePosted is usually managed by the server
    };
  }
}
