package org.bounswe.jobboardbackend.exception;
import org.springframework.http.HttpStatus;

public enum ErrorCode {


    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    MALFORMED_JSON(HttpStatus.BAD_REQUEST),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    AUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED),
    RESOURCE_CONFLICT(HttpStatus.CONFLICT),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_NOT_VERIFIED(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    USER_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),

    USER_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USERNAME_ALREADY_USED(HttpStatus.CONFLICT),
    EMAIL_ALREADY_USED(HttpStatus.CONFLICT),
    ROLE_INVALID(HttpStatus.UNAUTHORIZED),

    EMPLOYER_ALREADY_ASSIGNED(HttpStatus.CONFLICT),
    EMPLOYER_REQUEST_ALREADY_EXISTS(HttpStatus.CONFLICT),
    EMPLOYER_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMPLOYER_REQUEST_ALREADY_RESOLVED(HttpStatus.CONFLICT),
    EMPLOYER_REQUEST_INVALID_ACTION(HttpStatus.BAD_REQUEST),
    EMPLOYER_REQUEST_NO_APPLICANT(HttpStatus.BAD_REQUEST),
    EMPLOYER_LINK_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKPLACE_OWNER_MINIMUM_REQUIRED(HttpStatus.BAD_REQUEST),

    CURRENT_PASSWORD_INVALID(HttpStatus.BAD_REQUEST),
    PASSWORD_SAME_AS_OLD(HttpStatus.BAD_REQUEST),

    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PROFILE_ALREADY_EXISTS(HttpStatus.CONFLICT),

    WORKPLACE_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKPLACE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND),
    REVIEW_ALREADY_EXISTS(HttpStatus.CONFLICT),
    REPLY_ALREADY_EXISTS(HttpStatus.CONFLICT),
    REPLY_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKPLACE_UNAUTHORIZED(HttpStatus.FORBIDDEN),

    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),

    EDUCATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    EXPERIENCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SKILL_NOT_FOUND(HttpStatus.NOT_FOUND),
    INTEREST_NOT_FOUND(HttpStatus.NOT_FOUND),

    IMAGE_FILE_REQUIRED(HttpStatus.BAD_REQUEST),
    IMAGE_CONTENT_TYPE_INVALID(HttpStatus.BAD_REQUEST),
    IMAGE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_TOKEN(HttpStatus.BAD_REQUEST),
    TOKEN_EXPIRED(HttpStatus.BAD_REQUEST),

    BAD_REQUEST(HttpStatus.BAD_REQUEST),

    JOB_APPLICATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    APPLICATION_ALREADY_EXISTS(HttpStatus.CONFLICT),
    MISSING_FILTER_PARAMETER(HttpStatus.BAD_REQUEST),

    JOB_POST_NOT_FOUND(HttpStatus.NOT_FOUND),
    JOB_POST_FORBIDDEN(HttpStatus.FORBIDDEN),
    JOB_POST_CORRUPT(HttpStatus.INTERNAL_SERVER_ERROR),

    CHAT_NOT_LINKED_TO_REVIEW(HttpStatus.CONFLICT),
    CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    MENTORSHIP_NOT_ACTIVE(HttpStatus.CONFLICT),
    RESUME_REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND),
    REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
    REVIEW_NOT_COMPLETED(HttpStatus.CONFLICT),
    UNAUTHORIZED_REVIEW_ACCESS(HttpStatus.FORBIDDEN),
    REQUEST_ALREADY_PROCESSED(HttpStatus.CONFLICT),
    MENTOR_UNAVAILABLE(HttpStatus.CONFLICT),
    ACTIVE_MENTORSHIP_EXIST(HttpStatus.CONFLICT),
    MENTEE_CAPACITY_CONFLICT(HttpStatus.CONFLICT),
    MENTOR_PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND),
    MENTOR_PROFILE_ALREADY_EXISTS(HttpStatus.CONFLICT);


    public final HttpStatus status;
    ErrorCode(HttpStatus status) { this.status = status; }
}
