package org.bounswe.jobboardbackend.exception;
import org.springframework.http.HttpStatus;

public enum ErrorCode {


    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    MALFORMED_JSON(HttpStatus.BAD_REQUEST),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    AUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED),
    RESOURCE_CONFLICT(HttpStatus.CONFLICT),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_NOT_VERIFIED(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    USER_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),

    USER_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USERNAME_ALREADY_USED(HttpStatus.CONFLICT),
    EMAIL_ALREADY_USED(HttpStatus.CONFLICT),
    ROLE_INVALID(HttpStatus.UNAUTHORIZED),

    CURRENT_PASSWORD_INVALID(HttpStatus.BAD_REQUEST),
    PASSWORD_SAME_AS_OLD(HttpStatus.BAD_REQUEST),

    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PROFILE_ALREADY_EXISTS(HttpStatus.CONFLICT),

    WORKPLACE_NOT_FOUND(HttpStatus.NOT_FOUND),
    WORKPLACE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    REVIEW_ALREADY_EXISTS(HttpStatus.CONFLICT),
    WORKPLACE_UNAUTHORIZED(HttpStatus.FORBIDDEN),

    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),

    EDUCATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    EXPERIENCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SKILL_NOT_FOUND(HttpStatus.NOT_FOUND),
    INTEREST_NOT_FOUND(HttpStatus.NOT_FOUND),

    IMAGE_FILE_REQUIRED(HttpStatus.BAD_REQUEST),
    IMAGE_CONTENT_TYPE_INVALID(HttpStatus.BAD_REQUEST),
    IMAGE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_TOKEN(HttpStatus.BAD_REQUEST),
    TOKEN_EXPIRED(HttpStatus.BAD_REQUEST),

    BAD_REQUEST(HttpStatus.BAD_REQUEST),

    JOB_APPLICATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    APPLICATION_ALREADY_EXISTS(HttpStatus.CONFLICT),
    MISSING_FILTER_PARAMETER(HttpStatus.BAD_REQUEST),

    JOB_POST_NOT_FOUND(HttpStatus.NOT_FOUND),
    JOB_POST_FORBIDDEN(HttpStatus.FORBIDDEN),
    JOB_POST_CORRUPT(HttpStatus.INTERNAL_SERVER_ERROR);


    public final HttpStatus status;
    ErrorCode(HttpStatus status) { this.status = status; }
}
