name: Jobboard Frontend Test Deployment (PR)

on:
  pull_request:
    branches:
      - dev
    paths:
      - "apps/jobboard-frontend/**"
      - ".github/workflows/frontend-deploy-test.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Jobboard frontend test deployment workflow triggered for PR"
